[project]
name = "hello-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.12"
dependencies = [
    "python-docx>=1.1.2",
    "langchain-openai==0.3.35",
    "pypdf>=6.1.3",
    "requests>=2.32.5",
    "ruff>=0.14.3",
    "starlette>=0.50.0",
    "uvicorn>=0.38.0",
    "pymupdf>=1.26.6",
    "pillow>=12.0.0",
]
