[project]
name = "hello-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.12"
dependencies = [
    "langchain-openai==0.3.35",
    "pypdf>=6.1.3",
    "ruff>=0.14.3",
]
